version: '3'

services:
  web:
    build: ./web
    volumes:
      - ./web/:/usr/src/app
    ports:
      - 3000:80
    environment:
      HOST: 0.0.0.0
      PORT: 80
      API_URL: http://api/
      API_URL_BROWSER: http://localhost:3001/api/
      MEDIA_URL: http://localhost:3003/
    command: npm run dev
  api:
    build: ./api
    volumes:
      - ./api/:/usr/src/app
    ports:
      - 3001:80
    environment:
      PORT: 80
      BRAWLSTARS_TOKEN: "${BRAWLSTARS_TOKEN}"
      BRAWLAPI_TOKEN: "${BRAWLAPI_TOKEN}"
      BRAWLAPI_URL: "${BRAWLAPI_URL}"
      BRAWLSTARS_URL: "${BRAWLSTARS_URL}"
      TRACKER_URL: http://clicker/clicker
      CLICKER_URL: ""
    command: npm run dev
  media:
    build: ./media
    volumes:
      - ./media/:/usr/src/app
    ports:
      - 3003:80
    environment:
      PORT: 80
      BRAWLAPI_TOKEN: "${BRAWLAPI_TOKEN}"
      BRAWLAPI_URL: "${BRAWLAPI_URL}"
    command: npm run dev
  tracker:
    build: ./tracker
    volumes:
      - ./tracker/:/usr/src/app
    ports:
      - 3002:80
    environment:
      PORT: 80
      DATABASE_URI: mysql2://brawltime:brawltime@db/brawltime
    command: npm run dev
  clicker:
    build: ./clicker
    volumes:
      - ./clicker/:/usr/src/app
    ports:
      - 3004:80
    environment:
      PORT: 80
      CLICKHOUSE_HOST: clickhouse
    command: sh -c "npm run dev:migrate && npm run dev"
  db:
    image: mariadb:10.5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: brawltime
      MYSQL_USER: brawltime
      MYSQL_PASSWORD: brawltime
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  adminer:
    image: adminer
    ports:
      - 8080:8080
  clickhouse:
    image: yandex/clickhouse-server:20.5
    ports:
      - 8123:8123
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
