[build]
  command = "export API_PREFIX=/.netlify/functions/ && export API_URL_BROWSER=$API_PREFIX && npm run generate:api && npm run build:functions && npm run generate"
  publish = "dist"
  functions = "functions/dist/lambdas"

[build.environment]
  GIT_LFS_ENABLED = "1"
