[build]
  command = "export TRACKER_URL='https://api01.brawlstarstime.ninja/tracker' && export API_PREFIX=/.netlify/functions/ && export API_URL_BROWSER=$API_PREFIX && npm run generate:api && npm run build:apps && npm run generate"
  publish = "dist"
  functions = "functions/dist"

[build.environment]
  GIT_LFS_ENABLED = "1"
