site_url: https://brawltime.ninja
logo_url: https://brawltime.ninja/icon.png

backend:
  name: github
  repo: schneefux/brawltimeninja
  open_authoring: true
  base_url: https://auth.brawltime.ninja
  auth_scope: public_repo

publish_mode: editorial_workflow

media_folder: web/static/images
public_folder: /images

# ref. https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: guides
    label: "Guides"
    label_singular: "Guide"
    folder: web/content/guides
    media_folder: "{{media_folder}}/guides"
    public_folder: "{{public_folder}}/guides"
    create: true
    identifier_field: id
    preview_path: "blog/guides/{{slug}}"
    summary: "{{title}}"
    fields:
      - name: id
        widget: string
      - name: title
        widget: string
      - name: author
        widget: string
      - name: description
        widget: string
      - name: body
        widget: markdown
      - name: image
        required: false
        widget: image
      - name: mode
        required: false
        widget: select
        options: [gemGrab, brawlBall, heist, bounty, siege, showdown, superCity, roboRumble, bigGame]
      - name: map
        required: false
        widget: string
  - name: brawlers
    label: "Brawlers"
    label_singular: "Brawler"
    folder: web/content/brawlers
    format: yml
    create: true
    identifier_field: name
    preview_path: "tier-list/brawlers/{{slug}}"
    fields:
      - name: name
        widget: string
      - name: gender
        required: false
        widget: select
        options: [f, m, t]
      - name: description
        label: "Brawler description"
        required: false
        widget: string
      - name: main
        label: "Main attack description"
        required: false
        widget: string
      - name: super
        label: "Super attack description"
        required: false
        widget: string
      - name: starpower1_name
        label: "Star Power 1 name"
        required: false
        widget: string
      - name: starpower1_description
        label: "Star Power 1 description"
        required: false
        widget: string
      - name: starpower2_name
        label: "Star Power 2 name"
        required: false
        widget: string
      - name: starpower2_description
        label: "Star Power 2 description"
        required: false
        widget: string
      - name: gadget1_name
        label: "Gadget 1 Name"
        required: false
        widget: string
      - name: gadget1_description
        label: "Gadget 1 description"
        required: false
        widget: string
      - name: gadget2_name
        label: "Gadget 2 Name"
        required: false
        widget: string
      - name: gadget2_description
        label: "Gadget 2 description"
        required: false
        widget: string
      - name: gadgets
        required: false
        widget: list
        summary: "{{fields.name}}"
        fields:
          - name: name
            widget: string
          - name: description
            widget: string
      - name: starpowers
        required: false
        widget: list
        summary: "{{fields.name}}"
        fields:
          - name: name
            widget: string
          - name: description
            widget: string
      - name: voicelines
        required: false
        widget: list
      - name: voiceactor
        required: false
        widget: string
      - name: skins
        required: false
        widget: list
        summary: "{{fields.name}}"
        fields:
          - name: name
            widget: string
          - name: model
            widget: image
          - name: gems
            required: false
            widget: number
            value_type: int
            min: 0
          - name: starpoints
            required: false
            widget: number
            value_type: int
            min: 0
          - name: archived
            required: false
            widget: boolean
          - name: brawlpass
            required: false
            widget: boolean
          - name: lunarbrawl
            required: false
            widget: boolean
          - name: note
            required: false
            widget: string
          - name: description
            required: false
            widget: string
  - name: maps
    label: "Competition Winner Maps"
    label_singular: "Competition Winner Map"
    folder: web/content/maps
    format: yml
    create: true
    identifier_field: date
    preview_path: "tier-list/{{mode}}/{{date}}"
    sortable_fields: [date]
    fields:
      - name: date
        pattern: ["\\d{4}\\-(0[1-9]|1[012])\\-(0[1-9]|[12][0-9]|3[01])", "Must be a YYYY-MM-DD date string"]
        widget: string
      - name: mode
        required: false
        widget: select
        options: [gemGrab, brawlBall, heist, bounty, siege, soloShowdown, duoShowdown, superCity, roboRumble, bigGame]
      - name: map
        widget: string
      - name: author
        required: false
        widget: string
      - name: image
        required: false
        widget: image
        media_folder: "{{media_folder}}/maps"
        public_folder: "{{public_folder}}/maps"
  - name: faq
    label: "Questions & Answers"
    label_singular: "Question"
    folder: web/content/faq
    media_folder: "{{media_folder}}/faq"
    public_folder: "{{public_folder}}/faq"
    format: frontmatter
    create: true
    identifier_field: id
    #preview_path:
    fields:
      - name: id
        widget: string
      - name: title
        widget: string
      - name: question
        widget: string
      - name: body
        widget: markdown
