name: Build all services

on:
  push:
    branches:
      - master

jobs:
  build-api:
    uses: schneefux/brawltimeninja/.github/workflows/build-service.yml@master
    with:
      service: api
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
  build-clicker:
    uses: schneefux/brawltimeninja/.github/workflows/build-service.yml@master
    with:
      service: clicker
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
  build-cube:
    uses: schneefux/brawltimeninja/.github/workflows/build-service.yml@master
    with:
      service: cube
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
  build-media:
    uses: schneefux/brawltimeninja/.github/workflows/build-service.yml@master
    with:
      service: media
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
  build-render:
    uses: schneefux/brawltimeninja/.github/workflows/build-service.yml@master
    with:
      service: render
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
  build-web:
    uses: schneefux/brawltimeninja/.github/workflows/build-service.yml@master
    with:
      service: web
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
