name: Build clicker Docker image

on:
  push:
    branches:
      - master
    paths:
      - "clicker/**"

jobs:
  build-clicker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      # GitHub Container Registry
      # https://github.com/docker/login-action#github-container-registry
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ./clicker/
          push: true
          tags: ghcr.io/schneefux/brawltime-clicker:latest
      - run: echo ${{ steps.docker_build.outputs.digest }}
